### ISSUE TITLE
Windows Progress

### ISSUE THREAD

**Issue by ahmediddma** [ahmediddma/congenial-guide#1]
- [x] العملاء/الموردين
    - [x] بيانات المؤسسة
    - [x] تعريف الفروع
    - [x] تعريف المخازن
    - [x] تعريف الاصناف
    - [x] تعريف الخزن
    - [x] مجموعات الاصناف
    - [x] الوحدات
    - [x] بيانات الدول
    - [x] بيانات المدن
    - [x] بيانات المناطق
    - [x] تعريف البنوك
    - [x] تعريف مجالات العمل
    - [x] المجموعات الضريبية
- [x] العملاء/الموردين
    - [x] بيانات العملاء/الموردين
    - [x] ارصدة حسابات العملاء/الموردين
    - [x] كشف حســـــاب عميل/مورد
    - [x] حركة اخر سداد للعملاء / للموردين
- [x] شئون الموظفين
    - [x] تعريف الادارات
    - [x] تعريف الاقسام
    - [x] تعريف الموظف
    - [x] دفع الرواتب
    - [x] الحوافز و الجزاءات
- [x] مبيعات و مشتريات
    - [x] فاتورة المشتريات
    - [x] فاتورة المبيعات
    - [x] مردود المشتريات
    - [x] مردود المبيعات
    - [x] فاتورة عرض السعر
    - [x] مخزون اول المدة
    - [x] اجمالي فواتير بحسب  نوع الفاتورة
    - [x] اجمالي فواتير  بحسب العملاء
    - [x] مبيعات ومشتريات  تفصيلية
    - [x] صافي مبيعات وارباح
    - [x] مبيعات ومشتريات موظف
    - [x] مبيعات مندوب خلال فترة
- [x] سندات
    - [x] سندات قبض خارجية
    - [x] سندات صرف خارجية
    - [x] عرض سندات القبض والصرف خارجية
    - [x] عرض سندات القبض والصرف داخلية
    - [x] سندات قبض داخلية
    - [x] سندات صرف داخلية
- [x] الحسابات
    - [x] شجرة الحسابات
    - [x] القيود اليومية
    - [x] كشف حساب
    - [x] حركة الصندوق اليومية
    - [x] ميزان المراجعة رئيسي
    - [x] ميزان المراجعة تحليلي
    - [x] أرباح وخسائر حسابات رئيسية
    - [x] أرباح وخسائر حسابات تحليلية
    - [x] ميزانية عمومية حسابات رئيسية
    - [x] ميزانية عمومية حسابات تحليلية
- [x] المخازن 
    - [x] النقل من مخزن الى آخر
    - [x] تسويات الجرد
    - [x] كشف جرد المخازن
    - [x] ارصدة المخزن حتى تاريخ
    - [x] حركـــة صنف محددة
    - [x] صنف باجمالي الحركــات
    - [x] الأصناف التي ستنتهي صلاحيتها
- [x] دعم اتخاذ القرار
    - [x] معدل الدوران والركود للأصناف
- [x] اجمالي بيع وشراء 
    - [x] الاجمالي جهات مختلفة
    - [x] اجمالي المبيعات والمشتريات
    - [x] اجمالي المبيعات والمشتريات جهة عمل أو عميل
- [x] المستخدمين
    - [x] اضافة مستخدمين
    - [x] صلاحيات المستخدمين
    - [x] تغيير كلمة المرور
    - [x] الرقابة على بيع وشراء الأصناف
- [x] الاعدادت
    - [x] الاعدادات
    - [x] العرض
    - [x] تفعيل البرنامج
    - [x] النسخ الاحتياطي واستعادة قاعدة البيانات
    - [x] عن البرنامج
- [x] باركود متعدد
- [x] طباعه باركود
- [x] طباعه ملصق
- [x] وظائف
- [x] الاعدادات
- [x] سند استلام راتب لموظف
- [x] اقرار ضريبي
- [x] حركة الصندوق اليومية داخلى
- [x] تسجيل الدخول
- [x] الشاشة الرئيسية

**Comment by AzzedineAbdo** [comment]
> - [x] العملاء/الموردين
>     - [x] بيانات المؤسسة
>     - [x] تعريف الفروع
>     - [x] تعريف المخازن
>     - [x] تعريف الاصناف
>     - [x] تعريف الخزن
>     - [x] مجموعات الاصناف
>     - [x] الوحدات
>     - [x] بيانات الدول
>     - [x] بيانات المدن
>     - [x] بيانات المناطق
>     - [x] تعريف البنوك
>     - [x] تعريف مجالات العمل
>     - [x] المجموعات الضريبية
> - [x] العملاء/الموردين
>     - [x] بيانات العملاء/الموردين
>     - [x] ارصدة حسابات العملاء/الموردين
>     - [x] كشف حســـــاب عميل/مورد
>     - [x] حركة اخر سداد للعملاء / للموردين
> - [x] شئون الموظفين
>     - [x] تعريف الادارات
>     - [x] تعريف الاقسام
>     - [x] تعريف الموظف
>     - [x] دفع الرواتب
>     - [x] الحوافز و الجزاءات
> - [x] مبيعات و مشتريات
>     - [x] فاتورة المشتريات
>     - [x] فاتورة المبيعات
>     - [x] مردود المشتريات
>     - [x] مردود المبيعات
>     - [x] فاتورة عرض السعر
>     - [x] مخزون اول المدة
>     - [x] اجمالي فواتير بحسب  نوع الفاتورة
>     - [x] اجمالي فواتير  بحسب العملاء
>     - [x] مبيعات ومشتريات  تفصيلية
>     - [x] صافي مبيعات وارباح
>     - [x] مبيعات ومشتريات موظف
>     - [x] مبيعات مندوب خلال فترة
> - [x] سندات
>     - [x] سندات قبض خارجية
>     - [x] سندات صرف خارجية
>     - [x] عرض سندات القبض والصرف خارجية
>     - [x] عرض سندات القبض والصرف داخلية
>     - [x] سندات قبض داخلية
>     - [x] سندات صرف داخلية
> - [x] الحسابات
>     - [x] شجرة الحسابات
>     - [x] القيود اليومية
>     - [x] كشف حساب
>     - [x] حركة الصندوق اليومية
>     - [x] ميزان المراجعة رئيسي
>     - [x] ميزان المراجعة تحليلي
>     - [x] أرباح وخسائر حسابات رئيسية
>     - [x] أرباح وخسائر حسابات تحليلية
>     - [x] ميزانية عمومية حسابات رئيسية
>     - [x] ميزانية عمومية حسابات تحليلية
> - [x] المخازن 
>     - [x] النقل من مخزن الى آخر
>     - [x] تسويات الجرد
>     - [x] كشف جرد المخازن
>     - [x] ارصدة المخزن حتى تاريخ
>     - [x] حركـــة صنف محددة
>     - [x] صنف باجمالي الحركــات
>     - [x] الأصناف التي ستنتهي صلاحيتها
> - [x] دعم اتخاذ القرار
>     - [x] معدل الدوران والركود للأصناف
> - [x] اجمالي بيع وشراء 
>     - [x] الاجمالي جهات مختلفة
>     - [x] اجمالي المبيعات والمشتريات
>     - [x] اجمالي المبيعات والمشتريات جهة عمل أو عميل
> - [x] المستخدمين
>     - [x] اضافة مستخدمين
>     - [x] صلاحيات المستخدمين
>     - [x] تغيير كلمة المرور
>     - [x] الرقابة على بيع وشراء الأصناف
> - [x] الاعدادت
>     - [x] الاعدادات
>     - [x] العرض
>     - [x] تفعيل البرنامج
>     - [x] النسخ الاحتياطي واستعادة قاعدة البيانات
>     - [x] عن البرنامج
> - [x] باركود متعدد
> - [x] طباعه باركود
> - [x] طباعه ملصق
> - [x] وظائف
> - [x] الاعدادات
> - [x] سند استلام راتب لموظف
> - [x] اقرار ضريبي
> - [x] حركة الصندوق اليومية داخلى
> - [x] تسجيل الدخول
> - [x] الشاشة الرئيسية
>
