### ISSUE TITLE
drop down is not working

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#10]
![dropdown](https://user-images.githubusercontent.com/55345662/64921201-849bb380-d7c0-11e9-801f-6e8a09a635ed.gif)

**Comment by ahmediddma** [comment]
دة حقل read only مش من المفترض انه يفتح دروب دون او يعمل اى حاجة بيشتغل select فقط

**Comment by ramiiddma** [comment]
لو شغال  read only
يبقا شيل ال drop down menu
و خليها field عادى

**Comment by ahmediddma** [comment]
دة limitation فى تصميم الداتا بيس  هتاثر على

**Comment by ramiiddma** [comment]
دى حاجه تناقشها مع ال manager+
 لان هو البياخد القرار مش انا

**Comment by ahmediddma** [comment]
يا عم و ربنا انا اللى مسؤل عن الحاجة ديه لو كان استاذ محمد كنت قولتلك help wanted و سالته لما اجى اعملها
بس ديه حاجة لسه هتتصلح كمان 3 4 اصدارات فى البرنامج و ممكن متتعملش كمان بسبب الداتا بيس كله متوقف على عمليه النقل اللى هنعملها من الداتا بيس القديمة  للجديدة

**Comment by ahmediddma** [comment]
https://github.com/ahmedflix25/IconRetailWPF/commit/30fab07d03601758da157665aebedb079241ce52
