### ISSUE TITLE
drop down menu is not working properly 

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#12]
drop down menu is not working in (تعريف الاصناف).. need 3 clicks to work
![dropdown](https://user-images.githubusercontent.com/55345662/64921461-b4988600-d7c3-11e9-9582-50fc48a09737.gif)

**Comment by ahmediddma** [comment]
مرتبطة ب https://github.com/ahmediddma/congenial-guide/issues/7
