### ISSUE TITLE
تعديل السعر فى شاشة الاصناف بعد اضافة واحدات لا يحدث بيانات الوحدات

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#13]
prices are not synced between (الوحدات و سعر الصرف)
![synced prices](https://user-images.githubusercontent.com/55345662/64921988-85851300-d7c9-11e9-9126-cd83b295b8d4.gif)

**Comment by ahmediddma** [comment]
كما هى فى القديم يمكن تعدلها لاحقا
