### ISSUE TITLE
discounts and taxes don't work

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#15]
discount and taxes don't affect prices and minimum order don't apply
![ظظ](https://user-images.githubusercontent.com/55345662/64922062-e19c6700-d7ca-11e9-994c-9c6577b94243.PNG)

**Comment by ahmediddma** [comment]
البيانات ديه بتطبق فى الفواتير فقط

**Comment by ramiiddma** [comment]
تمام
