### ISSUE TITLE
لا يمكن اضافة صنف بنفس رقم صنف اخر محذوف

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#16]
if you deleted an item you can't add it again 
![deleted number](https://user-images.githubusercontent.com/55345662/64922175-6d62c300-d7cc-11e9-96b3-a85d8f0af2e0.gif)

**Comment by ahmediddma** [comment]
لان الصنف مش بيتحذف بشكل فعلى و لكن بيتم اخفائه فقط من المستخدم لانه مستخدم فى تقارير و اجزاء اخرى من البرنامج

**Comment by ramiiddma** [comment]
تمام دى تبقا مشكله  design من البرنامج الاولانى

**Comment by ahmediddma** [comment]
مينفعش تسجل اى حاجة بنفس رقم حاجة موجودة قبل كدة فى اى مكان فى البرنامج علشان دة identifier ليها و لازم يكون unique 
و انه مش بيحذف بشكل فعلى مش مشكله لان التصميم مطلوب يبقى كدة لانه حتى بعد حذف لسه بيظهر فى تقارير و فى امكان تانية فى البرنامج ايام لما كان لسه مستخدم لو اتحذف نهائى الحاجة ديه هتظهر فاضية او هتجيب ايرور

**Comment by ramiiddma** [comment]
ممكن الحاجه التتمسح تتحط فى list
تانيه بحيث ان كل list 
يبقا ليها ال id 
بتاعها و ماياثروش على بعض

**Comment by ahmediddma** [comment]
مينفعش يتنقل فى مكان تانى لان ساعتها هيبقى كانه اتحذف بالنسبه للداتا التانية 
هى بتعرفه من الرقم جوة الجدول بتاعها 
![Untitled](https://user-images.githubusercontent.com/51739190/64971494-129e9980-d8a8-11e9-9110-16db0012f423.png)
و حتى لو نفع ازاى الجدول التانى هيعرف انت بتطلب رقم حاجة محذوف ولا عاديه منين علشان يروح يجبها
