### ISSUE TITLE
drop down is not working in (تعريف الخزن)

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#18]
![drop down](https://user-images.githubusercontent.com/55345662/64922303-237adc80-d7ce-11e9-967b-8720ad45ba8e.gif)

**Comment by ahmediddma** [comment]
نفس https://github.com/ahmediddma/congenial-guide/issues/10

**Comment by ramiiddma** [comment]
نفس تعليق #10

**Comment by ahmediddma** [comment]
نفس رد https://github.com/ahmediddma/congenial-guide/issues/10 https://github.com/ahmediddma/congenial-guide/issues/10#issuecomment-531820020
