### ISSUE TITLE
شجرة  المجموعات لا تظهر التحديث بعد التعديلات (مجموعه الاصناف)

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#19]
![magmo3t el asnaf](https://user-images.githubusercontent.com/55345662/64922334-84a2b000-d7ce-11e9-812c-d42ef81ea09a.gif)

**Comment by ahmediddma** [comment]
https://github.com/ahmedflix25/IconRetailWPF/commit/a991e09c0d904708e19197bac7e4eb2ec5caf250
