### ISSUE TITLE
you can't edit an item مجموعات الاصناف

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#20]
![magmo3t el asnaf edit](https://user-images.githubusercontent.com/55345662/64922403-27f3c500-d7cf-11e9-9c1d-a00854c85fa6.gif)

**Comment by ahmediddma** [comment]
نفس https://github.com/ahmediddma/congenial-guide/issues/19

**Comment by ramiiddma** [comment]
duplicated so we don't forget it in developing or retesting

**Comment by ahmediddma** [comment]
هما الاتنين نفس المشكلة لما تتصلح هتصلح الاتنين

**Comment by ahmediddma** [comment]
https://github.com/ahmediddma/congenial-guide/issues/19
