### ISSUE TITLE
automatic counting don't reset مجموعات الاصناف

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#21]
if you delete all items and try to add new item counting doesn't reset
![magmo3t el asnaf count](https://user-images.githubusercontent.com/55345662/64922431-69847000-d7cf-11e9-8262-171a44a75497.PNG)

**Comment by ahmediddma** [comment]
علشان دة id بيعد لواحدة ملهوش علاقه فيه مجموعات ولا لا
