### ISSUE TITLE
duplicated item شاشة المدن

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#25]
you can add duplicated items
![duplicate](https://user-images.githubusercontent.com/55345662/64922660-fa5c4b00-d7d1-11e9-9956-daed7c33f283.gif)

**Comment by ahmediddma** [comment]
نفس https://github.com/ahmediddma/congenial-guide/issues/23 لان فيه مدن بنفس الاسم

**Comment by ramiiddma** [comment]
بس مافيش دولتين بنفس الاسم

**Comment by ahmediddma** [comment]
علشان الجنسية شرحها هناك فى شاشة الدول ممكن يضيف دول مصر مرتين بجنسيه مصري و مصرية بردة دة محدودية فى الداتا بيس المفروض كانت تكون جدول لواحدها للجنسيات و لكن هنا كلها واحدة ممكن تتعمل فى تحديث مستقبلى
