### ISSUE TITLE
شاشة المؤسسه مشكلة فى كنترول الارقام

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#3]
ctrl + z is not working in case you want to select previous rate
![s3r el sarf](https://user-images.githubusercontent.com/55345662/64920435-03402300-d7b8-11e9-80eb-e2e59a5afefc.gif)

**Comment by ahmediddma** [comment]
مشكلة فى مكتبة mahapps

**Comment by ramiiddma** [comment]
تمام
