### ISSUE TITLE
زر التعديل لا يعمل عند اختيار مورد/عميل من شاشة مورد عميل + زر الاضافة يكون مفعل

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#31]
![edit](https://user-images.githubusercontent.com/55345662/64923317-13b4c580-d7d9-11e9-9635-1e186ac51786.gif)

**Comment by ahmediddma** [comment]
half done

**Comment by ahmediddma** [comment]
مشكله التعديل بسبب الداتا بيز هتتصلح قريب لما اعدل التصميم
