### ISSUE TITLE
لا يوجد رساله تخبر المستخدم انه لم يعثر على شئ عند البحث فى شاشة كشف حساب عميل مورد

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#32]
![nothing](https://user-images.githubusercontent.com/55345662/64923393-d13fb880-d7d9-11e9-9074-ce198af0ddf4.gif)

**Comment by ahmediddma** [comment]
اضافة رساله تخبر المستخدم انه لم يتم العثور على بيانات
