### ISSUE TITLE
when choosing a date day 15 is always marked

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#33]
![15](https://user-images.githubusercontent.com/55345662/64923420-1532bd80-d7da-11e9-952e-030cff4f9124.gif)

**Comment by ahmediddma** [comment]
تخبر المستخدم بتاريخ اليوم

**Comment by ramiiddma** [comment]
تبقا بلون تانى للتمييز

**Comment by ahmediddma** [comment]
مكتبة خارجية https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit

**Comment by ahmediddma** [comment]
there is a work around now and just a work around
