### ISSUE TITLE
رساله جارى تحميل البيانات تظل ظاهره عند وجود مشكلة شاشة حركة اخر سداد للعملاء

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#34]
![freeze](https://user-images.githubusercontent.com/55345662/64923723-19aca580-d7dd-11e9-8f3f-e794aa573692.gif)

**Comment by ahmediddma** [comment]
حل المشكلة 
الغاء الرساله عند وجود مشكلة تلقائى و اخبار المستخدم

**Comment by ahmediddma** [comment]
تحدث المشكله عندما لا يكون هناك بيانات لعرضها
