### ISSUE TITLE
date is always marked and wrong inputs (تعريف الموظفين)

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#38]
date 16 is always marked and you can set both born date and hiring date to the same day,month and year
![born 16](https://user-images.githubusercontent.com/55345662/64945721-7fe30800-d871-11e9-9f60-d9a1da8795d8.PNG)

**Comment by ahmediddma** [comment]
نفس https://github.com/ahmediddma/congenial-guide/issues/33 واحدة لاخبار المستخدم بتاريخ اليوم و الاخرى اختياره

**Comment by ahmediddma** [comment]
work around added but it's work a workaround and not an actual solution
