### ISSUE TITLE
application crash when press a button (دفع الرواتب )

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#39]
press (عرض) button
![crash](https://user-images.githubusercontent.com/55345662/64947558-93906d80-d875-11e9-8148-51f6a56b15eb.gif)

**Comment by ahmediddma** [comment]
غالبا مرتبطه ب https://github.com/ahmediddma/congenial-guide/issues/34

**Comment by ahmediddma** [comment]
تحدث مشكله عندما لا يكون هناك اضافى لاعادته من الداتا بيز
