### ISSUE TITLE
English language is not working

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#4]
there is an option to select English language but still appear in Arabic

**Comment by ahmediddma** [comment]
لسه متحددش اللغه الانجليزية هتضاف ولا لا و بالتالى مفيش انجليزى

**Comment by ramiiddma** [comment]
اللغه الانجليزيه مش مطلوبه يبقا الاختيار يتشال اصلا

**Comment by ahmediddma** [comment]
تصميم الشاشة منقول كما هو من القديم

**Comment by ramiiddma** [comment]
تمام القديم كان فيه مشاكل و نقلتها منه نسيبه بمشاكله ولا نحلها علشان نعلى بالجوده؟

**Comment by ahmediddma** [comment]
مش فكرة نقلتها بمشاكله القديم كان فيه عربى انجليزى (بس ايوة معظم الحاجة منقولة زى ما هى بمشاكلها همتك معانا) و حد شال الانجليزى مش اكتر عموما هشلها
