### ISSUE TITLE
you can't add a client (سندات قبض داخليه)

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#42]
![client](https://user-images.githubusercontent.com/55345662/64949743-29c69280-d87a-11e9-9805-83a9c9af4481.gif)

**Comment by ahmediddma** [comment]
غالبا مرتبطه ب https://github.com/ahmediddma/congenial-guide/issues/26

**Comment by ahmediddma** [comment]
done https://github.com/ahmedflix25/IconRetailWPF/commit/4c5220808fafde1b91f081d858f4896709d27d1d
