### ISSUE TITLE
language selection is not working properly 

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#5]
when changing language you need to restart the application to work

**Comment by ahmediddma** [comment]
مرتبطة ب https://github.com/ahmediddma/congenial-guide/issues/4

**Comment by ramiiddma** [comment]
تمام شوف المطلوب هيتضاف لغه ولا لا لو هيتضاف صلحها مش هيتضاف شيل الاختيار بس بلغ العميل فى حاله اضافه لغه فى المستقبل المشكله دى هتكون موجوده
