### ISSUE TITLE
قايمه الcombobox مش بتفتح فى الdatagrid من اول ضغطه

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#7]
sometimes you can't close it other times you can't open it and sometimes it automatically adds a new field
![drop down](https://user-images.githubusercontent.com/55345662/64920756-5071c400-d7bb-11e9-8805-4c0673709177.gif)

![drop down2](https://user-images.githubusercontent.com/55345662/64920759-549de180-d7bb-11e9-87d6-148b958a0b01.gif)

**Comment by ahmediddma** [comment]
اضافة one click to edit cell ليها لحل المشكلة
