### ISSUE TITLE
you can't add stores to the same branch

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#8]
you can't add stores to the same branch even if you marked the store is not working any more which is logically wrong 

![ma5azn](https://user-images.githubusercontent.com/55345662/64920943-6bddce80-d7bd-11e9-963d-2c11f1018113.gif)

**Comment by ahmediddma** [comment]
البرنامج مش بيتاكد من الحالة لما بييجى يضيف جديد بيتاكد اذا كان افتراضى فقط ولا لا 
فلو كان فيه واحد افتراضى حتى لو متوقف مش هيضيف تانى
