### ISSUE TITLE
شاشة تعريف المخازن يمكن اضافة مستخدم اكتر من مرة للمخزن

### ISSUE THREAD

**Issue by ramiiddma** [ahmediddma/congenial-guide#9]
you can add employees more than once and you can't update it
![employees](https://user-images.githubusercontent.com/55345662/64921181-2c64b180-d7c0-11e9-96d9-7d0b2ce6e68f.gif)

**Comment by ahmediddma** [comment]
البرنامج بيعرف ان فيه موظف اضاف اكتر من مرة و بيضيفه مرة واحدة بس

**Comment by ramiiddma** [comment]
تمام ظبطها انه مايقبلش من الاساس نفس الموظف اكتر من مره
